# promtail/promtail-config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # ---- Docker containers (json-file driver) ----
  - job_name: docker
    pipeline_stages:
      - docker: {}     # parses docker json logs into proper line/timestamp/stream
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

  # ---- Custom app logs (drop files into ./promtail/logs) ----
  - job_name: app-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: app-logs
          app: news-ingester
          # Globs are supported; e.g. .log, .jsonl, .txt
          __path__: /logs/**/*

    # Example JSON pipeline for structured logs (optional)
    # Enable if your files are JSON lines with fields like ts, level, msg, source, ticker, price, url, etc.
    # pipeline_stages:
    #   - json:
    #       expressions:
    #         ts: ts
    #         level: level
    #         msg: msg
    #         source: source
    #         ticker: ticker
    #         price: price
    #         url: url
    #   - labels:
    #       level:
    #       source:
    #       ticker:
    #   - timestamp:
    #       source: ts
    #       format: RFC3339