version: "3.8"

name: monitoring-stack

services:
  prometheus:
    image: prom/prometheus:latest  # Prometheus time-series database and scraper
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"                # Expose Prometheus UI on host: http://localhost:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro   # Main config
      - ./prometheus/rules:/etc/prometheus/rules:ro                     # Alerting/recording rules
      - prometheus-data:/prometheus                                     # Persistent TSDB storage
    command:
      # Enable external config, adjust scrape/TSDB retention, and load rules.
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d        # Keep 15 days of metrics; adjust to your needs
      - --web.enable-lifecycle                   # Allows POST /-/reload to hot-reload config
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"                # Alertmanager UI on host: http://localhost:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro  # Routing + receivers
      - alertmanager-data:/alertmanager                                       # Silences & state
    networks:
      - monitoring
 
  # -------------------------------------------
  # Loki: log storage & query engine (single-node)
  # -------------------------------------------
  loki:
    image: grafana/loki:2.9.6
    container_name: loki
    restart: unless-stopped
    command: [ "-config.file=/etc/loki/loki-config.yml" ]
    ports:
      - "3100:3100"             # Loki HTTP API (query/push): http://localhost:3100
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki         # TSDB + index storage
    networks:
      - monitoring

  # -------------------------------------------
  # Promtail: ships container & file logs to Loki
  # -------------------------------------------
  promtail:
    image: grafana/promtail:2.9.6
    container_name: promtail
    restart: unless-stopped
    command: [ "-config.file=/etc/promtail/promtail-config.yml" ]
    volumes:
      # Read Docker logs (json-file driver)
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Your extra log directories can be mounted under ./promtail/logs (host)
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ./promtail/logs:/logs:ro
    depends_on:
      - loki
    networks:
      - monitoring
  
  # Exposes BTC wallet balances as Prometheus metrics on :9108
  btc-wallet-exporter:
    # Option 1: use a locally built image (from the exporter repo you just built)
    image: btc-wallet-exporter:latest
      # Option 2 (alternative): build here (uncomment if you want compose to build it)
      # build:
      #   context: ./btc-wallet-exporter
      #   dockerfile: Dockerfile
    container_name: btc-wallet-exporter
    restart: unless-stopped
    ports:
      - "9108:9108"                       # expose metrics/healthz to host (optional)
    volumes:
      - ./btc-wallet-exporter/config.yml:/config.yml:ro  # your addresses & settings
    environment:
      # (Optional) override config via flags/env if you want:
      # - BTC_EXPORTER_INTERVAL=30s
      # - BTC_EXPORTER_LOG=info
      # Not required when using config.yml.
      - TZ=UTC
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"                # Grafana UI on host: http://localhost:3000
    environment:
      # Admin credentials (override via .env to avoid hardcoding)
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      # Enable Prometheus-style /metrics for Grafana itself (scraped by Prometheus)
      - GF_METRICS_ENABLED=true
      # Load provisioning files on startup
      - GF_PATHS_PROVISIONING=/usr/share/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana                                     # Persistent Grafana data
      - ./grafana/grafana.ini:/usr/share/grafana/grafana.ini:ro                 # Base Grafana config
      - ./grafana/provisioning:/usr/share/grafana/provisioning:ro               # Datasources & dashboards
   #   - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards:ro 
    depends_on:
      - prometheus
    networks:
      - monitoring


#btc-wallet-exporter:
#  image: btc-wallet-exporter:latest
#  container_name: btc-wallet-exporter
#  restart: unless-stopped
#  ports:
#    - "9108:9108"
#  volumes:
#    - ./btc-wallet-exporter/config.yml:/config.yml:ro
#  networks:
#    - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    # Use bridge networking and publish 9100 so Prometheus can reach it at "node-exporter:9100".
    ports:
      - "9100:9100"
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro,rslave
    networks:
      - monitoring

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    restart: unless-stopped
    command:
      - -retentionPeriod=5y            # keep 5 years; pick your horizon
      - -selfScrapeInterval=0s        # optional, reduces self-metrics noise
    ports:
      - "8428:8428"                   # HTTP API (write/read/UI)
    volumes:
      - vm-data:/storage              # persistent TSDB data
    networks:
      - monitoring



networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:
  vm-data:
  loki-data:
