# Main Prometheus configuration
global:
  scrape_interval: 15s     # How often to scrape targets (default 1m). 15s is common for infra.
  evaluation_interval: 15s # How often to evaluate alerting/recording rules.
  scrape_timeout: 10s

rule_files:
  # Load all alerting/recording rules from the rules folder
  - /etc/prometheus/rules/*.yml

remote_write:
  - url: http://victoria-metrics:8428/api/v1/write
    # Optional tuning:
    queue_config:
      capacity: 20000
      max_samples_per_send: 5000
      max_shards: 4

alerting:
  alertmanagers:
    # Send alerts to Alertmanager service (compose DNS: "alertmanager")
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  # Scrape Prometheus itself (useful meta-metrics)
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape Alertmanager for its own metrics
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  # Scrape Grafana metrics (enabled via GF_METRICS_ENABLED=true)
  - job_name: "grafana"
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana:3000"]

  # Scrape Node Exporter running on the host
  # If you used network_mode: host for node-exporter, scrape localhost:9100.
  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]  # If you exposed node-exporter via ports, use "node-exporter:9100"
    # Optional: add relabeling to attach useful labels such as the host name
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "host-machine"  # Change to a custom label if desired

  # BTC wallet exporter (your custom Go service)
  - job_name: "btc-wallet-exporter"
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ["btc-wallet-exporter:9108"]  # compose service name + port

