apiVersion: 1
datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    isDefault: false            # keep Prometheus as default, or flip this if you prefer
    url: http://victoria-metrics:8428
    jsonData:
      httpMethod: POST